### ISSUE TITLE
another conflict with gnome-python2

### ISSUE THREAD

**Issue by raveit65** [mate-desktop-legacy-archive/python-mate-desktop#1]
Hi Stefano,
i 've found another conflict file with gnome-python2  :(
/usr/lib64/python2.7/site-packages/gtk-2.0/wnck.so
My package mate-python2-libwnck-1.1.0-2.fc16.x86_64 and gnome-python2-libwnck-2.32.0-5.fc16.x86_64 provide this file.
In a standard fedora installation  gnome-python2-libwnck is a dependency of ocra.
But for a correct working mintnenu i need mate-deskbar-applet which has mate-python2-libwnck as a dependency.
Or is this a nonsens dependency?

I already use "--datadir=/usr/share/mate-defs"  configure flag to build mate-python and mate-python-desktop to avoid conflicts with gnome-python2,  but this conflict i can't solve in the rpmbuild process.
In my eyes the conflicting files have to be renamed.
This is a serious problem, a lot's of mate packages need a correct working python section.

I'm really wondering that this python issues only occurs in fedora at the moment.

**Comment by raveit65** [comment]
directory move patch:
http://dl.dropbox.com/u/49862637/Mate-desktop/mate-python-desktop_change-directories.patch
Same work as in the mate-python patch.
In the fedora version of python-mate-desktop aren't not all parts during compile enable. (egg. totem,..)
Maybe this patch must be extended if you used all parts to avoid package conflicts.

**Comment by stefano-k** [comment]
you need to build with those flags:

  --disable-static \
  --enable-applet \
  --enable-cajaburn \
  --enable-matekeyring \
  --enable-matedesktop \
  --enable-mateprint \
  --enable-mateprintui \
  --enable-marco \
  --disable-rsvg \
  --disable-bugbuddy \
  --disable-mediaprofiles \
  --disable-wnck \
  --disable-gtop \
  --disable-gtksourceview \
  --disable-totem_plparser \
  --disable-evolution \
  --disable-evolution_ecal \
  --disable-evince \
  --disable-braseroburn \
  --disable-braseromedia

Check here: https://github.com/mate-desktop/debian-packages/blob/master/python-mate-desktop/debian/rules

**Comment by raveit65** [comment]
Ok,
but where do i find this build requires?
configure.ac
m4_define(libmateprint_required_version,     1.1.0)
m4_define(libmateprintui_required_version,   1.1.0)
m4_define(libcaja_burn_required_version,  1.1.0)

and why not evolution?
Is the reason that evolution build with gtk3 ?

**Comment by stefano-k** [comment]
```
checking for LIBMATEPRINT... no
checking for LIBMATEPRINTUI... no
checking for CAJABURN... no
```

those requirements do not exist yet, so mateprint and brasero stuff will be disabled automatic.

```
The following modules will NOT be built
mateprint
mateprint.ui
cajaburn
```

About evolution, we dont build it because it's not part of MATE.
